apiVersion: v1
kind: Service
metadata:
  name: nexus
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector:
    app: nexus
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081

---  
kind: Endpoints
apiVersion: v1
metadata:
  name: nexus
subsets:
  - addresses:
      - ip: "127.0.0.1"
    ports:
      - port: 8081
   

